helmDefaults:
  wait: false
  args:
  - "-v=7"

repositories:
- name: incubator
  url: "https://kubernetes-charts-incubator.storage.googleapis.com/"

releases:
- name: config
  namespace: default
  chart: incubator/raw
  values:
  - resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: auth
        labels:
          deployment.kcos.keysight.com/namespace: auth
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: app2ns
        labels:
          deployment.kcos.keysight.com/namespace: app2ns
- name: operator
  namespace: auth
  chart: ./charts/keycloak-operator
  needs:
  - default/config
- name: webpage
  namespace: auth
  chart: bitnami/nginx
  needs:
  - default/config
  values:
  - ingress:
      enabled: true
      hosts:
      - name:
        path: /
    staticSiteConfigmap: sso-my-keycloak-web-data
- name: sso
  namespace: auth
  chart: ./charts/my-keycloak
  needs:
  - auth/operator
- name: app
  # TODO: other ns?
  namespace: auth
  chart: ./charts/mock-app
  needs:
  - auth/operator
  values:
  - keycloak:
      internalBaseUrl: http://kcos-framework-v1-nginx-ingress-controller.kcos-framework.svc
      realmLabels:
        app.kubernetes.io/name: my-keycloak
        app.kubernetes.io/instance: sso
- name: app2
  # TODO: other ns?
  namespace: app2ns
  chart: ./charts/mock-app
  needs:
  - auth/operator
  values:
  - keycloak:
      namespace: auth
      internalBaseUrl: http://kcos-framework-v1-nginx-ingress-controller.kcos-framework.svc
      realmLabels:
        app.kubernetes.io/name: my-keycloak
        app.kubernetes.io/instance: sso
    ingress:
      paths:
      - /mock-different-app/
