apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webapp.fullname" . }}
  labels:
{{ include "webapp.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "webapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "webapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      subdomain: {{ include "webapp.fullname" . }}
      serviceAccountName: {{ template "webapp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: web-data
          configMap:
            name: {{ include "webapp.fullname" . }}-web-data
        - name: client-secret
          secret:
            secretName: keycloak-client-secret-{{- include "webapp.clientId" . }}
            optional: true
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: WEB_CONCURRENCY
            value: "2"
          - name: LOG_LEVEL
            value: debug
          - name: MOCKAPP_CLIENT_ID
            value: {{ quote (include "webapp.clientId" .) }}
          - name: MOCKAPP_IDP_PATH
            value: {{ quote (include "webapp.idpPath" .) }}
          - name: MOCKAPP_INTERNAL_BASE_URL
            value: {{ .Values.keycloak.internalBaseUrl | quote }}
          - name: MOCKAPP_FULLNAME
            value: {{ quote (include "webapp.fullname" .) }}
{{- with $ingress := .Values.ingress }}
  {{- range $idx, $path := $ingress.paths }}
          - name: MOCKAPP_SELF_PATH_{{ $idx }}
            value: {{ $path | quote }}
  {{- end }}
{{- end }}
          volumeMounts:
            - name: web-data
              mountPath: /app
            - name: client-secret
              mountPath: /run/secrets/mock-app/client
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
