{{- if .Values.ingress.enabled -}}
{{- $fullName := include "webapp.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "webapp.labels" . | indent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- with $ingress := .Values.ingress }}
    {{- range $path := $ingress.paths }}
      {{- range $host := $ingress.hostnames }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: {{ $path }}(.*)
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
