apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: {{ include "webapp.fullname" . }}-mock-web-client
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  realmSelector:
    matchLabels:
      {{- toYaml .Values.keycloak.realmLabels | nindent 6 }}
  client:
    clientId: {{ .Values.keycloak.clientId }}
    protocol: openid-connect
{{/* TODO: ("https:" or "http:" + $host.host) prefix, if $host.host given */}}
    redirectUris:
{{- with $ingress := .Values.ingress }}
  {{- range $path := $ingress.paths }}
    {{- range $host := $ingress.hostnames }}
      - {{ $path }}callback/
    {{- end }}
  {{- end }}
{{- end }}
    implicitFlowEnabled: true
    standardFlowEnabled: true
