apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: {{ include "webapp.fullname" . }}-mock-web-client
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  realmSelector:
    matchLabels:
      {{- toYaml .Values.keycloak.realmLabels | nindent 6 }}
  client:
    clientId: mock-web-app
    protocol: openid-connect
    redirectUris:
      - /mock-app/
    implicitFlowEnabled: true
    standardFlowEnabled: true
