{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "webapp.serviceAccountName" . }}
  labels:
{{ include "webapp.labels" . | indent 4 }}
{{- end -}}
