apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: {{ include "my-keycloak.fullname" . }}
  labels:
    {{- include "my-keycloak.labels" . | nindent 4 }}
spec:
  realm:
    id: "keysight"
    realm: "keysight"
    enabled: True
    displayName: "Keysight"
    users:
      - username: "admin"
        firstName: "Default"
        lastName: "Admin"
        email: "admin@example.org"
        credentials:
          - temporary: false
            type: password
            value: "admin"
        enabled: True
        emailVerified: False
        realmRoles:
          - "offline_access"
          - "uma_authorization"
        clientRoles:
          account:
            - "manage-account"
            - "view-profile"
          realm-management:
            - "manage-realm"
            - "manage-identity-providers"
            - "manage-users"
            - "manage-authorization"
            - "query-clients"
            - "view-clients"
  instanceSelector:
    matchLabels:
      {{- include "my-keycloak.labels" . | nindent 6 }}
