apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: {{ include "my-keycloak.fullname" . }}
  labels:
    {{- include "my-keycloak.labels" . | nindent 4 }}
spec:
  realm:
    id: "keysight"
    realm: "keysight"
    enabled: True
    displayName: "Keysight Device"
  instanceSelector:
    matchLabels:
      {{- include "my-keycloak.labels" . | nindent 6 }}
